### ISSUE TITLE
no macOS support?

### ISSUE THREAD

**Issue by leonyaaaaaaa** [Kron4ek/minecraft-vortex-launcher#54]
really love your launcher
whoud be nice to see it on macos

**Comment by Kron4ek** [comment]
There is a macOS version [in the form of source code](https://github.com/Kron4ek/minecraft-vortex-launcher/blob/master/vlauncher_macos.pb), which can be manually compiled with PureBasic. It is untested though, since i do not have any hardware with macOS installed. And the last time I tried macOS in a virtual machine (qemu), it had limited OpenGL capabilities that weren't enough to run Minecraft.

**Comment by leonyaaaaaaa** [comment]
не разобрался с компилированем,
ладно, пойду использовать tlauncher'ом bloatvar'ным
