### ISSUE TITLE
I cant play multiplayer (LAN)

### ISSUE THREAD

**Issue by Legnatbird** [Kron4ek/minecraft-vortex-launcher#63]

**Comment by Kron4ek** [comment]
LAN multiplayer with a dedicated server should work, i tested it multiple times. The in-game "Open to LAN" function may or may not work, and in case it does not work for you, run a dedicated server. Make sure to disable `online-mode` in the server settings, otherwise you will get "Invalid session" error when connecting to it.

**Comment by Legnatbird** [comment]
How i can setup a dedicate server to play with hamachi?

**Comment by Kron4ek** [comment]
I don't know for sure as i'm not very familiar with Hamachi, but I think you can set the server up the same way as you would without Hamachi.
